#! /bin/sh

#. "${HOME}/.cache/wal/colors.sh"


bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width         2
bspc config window_gap          12
bspc config top_padding		18
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config removal_adjustment   none

bspc rule -a qutebrowser desktop='^2'
bspc rule -a Wine state=floating

start-pulseaudio-x11
sxhkd &
$HOME/.config/polybar/launch.sh &
xset +fp /usr/share/fonts/misc &
xset +fp ~/.fonts &
xset fp rehash &
xsetroot -cursor_name left_ptr &
xrdb ~/.Xresources

wal -R
#wal -i '/home/sambow23/Pictures/sanfran.jpg'
feh --bg-fill '/home/sambow23/Documents/hl.png'

# Pulse Audio controls
#XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume 0 +5% #increase sound volume
#XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume 0 -5% #decrease sound volume
#XF86AudioMute exec --no-startup-id pactl set-sink-mute 0 toggle # mute sound

#xinput set-prop 11 296 -0
#albert &
#tint2 &
nm-applet &
#xfce4-panel &
picom &
/usr/lib/xfce4/notifyd/xfce4-notifyd
blueman-manager &

#/home/sambow23/comptray/comptray &
#compton --backend glx --paint-on-overlay --vsync opengl-swc

